### ISSUE TITLE
[PE-D][Tester D] Allow arbitrarily ordered arguments

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113T-W11-2/tp#166] opened 2023-11-03 16:54 UTC
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/charkty/ped/main/files/08caa46b-93a6-4a38-92bc-61f015f41162.png)

Recommended to give more flexibility by allowing the mix of orders in input of the flags. Otherwise, explicitly state in UG that it has to be entered in that fixed order.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: charkty/ped#8

**Comment by lctxct** [comment] 2023-11-05 11:43
Duplicate of https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/148.

**Comment by lctxct** [comment] 2023-11-05 11:45
Duplicate of https://github.com/AY2324S1-CS2113T-W11-2/tp/issues/148

**Comment by woodenclock** [comment] 2023-11-09 14:33
I think this just needs a bit of tweaking the add command???
Edit: I take back what I said, it's gonna take quite a bit of change.

**Comment by woodenclock** [comment] 2023-11-09 15:12
I think we just state in the UG that the order of the arguments are fixed.

**Comment by woodenclock** [comment] 2023-11-11 14:04
Yup, stated in UG
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/08b61d37-1479-485b-93aa-4042f727c880)

**Comment by woodenclock** [comment] 2023-11-11 14:04
![image](https://github.com/AY2324S1-CS2113T-W11-2/tp/assets/69474977/8179f6a9-1351-4023-95ad-00fb15702364)

**Closed as completed by woodenclock** 2023-11-11 14:04 UTC
Labels: priority.Low, type.Review
